### ISSUE TITLE
netbean python plugin download issue 

### ISSUE THREAD

**Issue by Roomi-32** [albilu/netbeansPython#119]
org.netbeans.modules.python.PythonCustomException: Error while installing dependencies!
	at org.netbeans.modules.python.Installer.lambda$restored$0(Installer.java:32)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)

**Comment by albilu** [comment]
Please provide informations using the template
